spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 처음 실행하면 테이블을 자동 생성 (운영 시엔 validate/none 권장)
    properties:
      hibernate:
        format_sql: true # 실행되는 SQL을 보기 좋게 출력

jwt:
  secret: bW9yZGF0aGVfMzJfYnl0ZXNfbG9uZ19zZWNyZXRfa2V5